[package]
name = "thistermination"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.23"
quote = "1.0.29"
proc-macro2 = "1.0.63"
regex = "1.9.1"